CREATE TABLE "nguoi_dung" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" BIGINT,
    -- Đã sửa: bigin -> BIGINT
    "user_name" VARCHAR(255),
    -- Đã sửa: varchar -> VARCHAR
    "password" VARCHAR(255),
    "email" VARCHAR(255)
);
CREATE TABLE "sinh_vien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "msv" BIGINT,
    -- Đã sửa: bigin -> BIGINT
    "user_name" VARCHAR(255),
    "password" VARCHAR(255),
    "email" VARCHAR(255)
);
CREATE TABLE "nckh_chuyen_mon" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ten_chuyen_mon" TEXT NOT NULL,
    "mo_ta" TEXT,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now(),
    -- Đã sửa: upadte_at -> update_at
    "deleted_at" TIMESTAMP
);
CREATE TABLE "nckh_chu_de" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ten_chu_de" TEXT NOT NULL,
    "mo_ta" TEXT,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now(),
    -- Đã sửa: upadte_at -> update_at
    "deleted_at" TIMESTAMP
);
CREATE TABLE "nckh_linh_vuc" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ten_linh_vuc" TEXT,
    "mo_ta_linh_vuc" TEXT,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now() -- Đã sửa: upadte_at -> update_at
);
CREATE TABLE "nckh_nha_khoa_hoc" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_name" BIGINT,
    "ho" TEXT,
    -- Đã sửa: string -> TEXT
    "ten" TEXT,
    -- Đã sửa: string -> TEXT
    "email" TEXT,
    -- Đã sửa: string -> TEXT
    "sdt" TEXT,
    -- Đã sửa: string -> TEXT
    "linh_vuc_id" BIGINT REFERENCES "nckh_linh_vuc" ("id"),
    "chuyen_gia" BOOLEAN DEFAULT FALSE,
    -- Đã sửa: bool -> BOOLEAN
    "chuyen_mon_id" BIGINT REFERENCES "nckh_chuyen_mon" ("id"),
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now(),
    -- Đã sửa: upadte_at -> update_at
    "deleted_at" TIMESTAMP,
    "status" INT
);
CREATE TABLE "nckh_thongbao_dexuat" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Sửa PK cho nhất quán
    "ten" TEXT,
    -- Đã sửa: string -> TEXT
    "noi_dung" TEXT,
    -- Đã sửa: longtext -> TEXT
    "ngaybatdau" DATE,
    "ngayketthuc" DATE,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now() -- Đã sửa: upadte_at -> update_at
);
CREATE TABLE "nckh_du_an" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ma" TEXT,
    "ten" TEXT,
    "cap_du_an" INTEGER,
    "thongbao_id" BIGINT REFERENCES "nckh_thongbao_dexuat" ("id"),
    "linhvuc_id" INT REFERENCES "nckh_linh_vuc" ("id"),
    "loai_hinh_nc" INT,
    "id_nguoitao" INT,
    "vai_tro" INT,
    "trang_thai" INT,
    "ngay_gui" TIMESTAMP,
    "ngay_ket_thuc" TIMESTAMP,
    "thoi_gian" INT,
    "kinh_phi" TEXT,
    -- Đã sửa: string -> TEXT
    "kinh_phi_duyet" TEXT,
    -- Đã sửa: string -> TEXT
    "url_thuyet_minh" TEXT,
    -- Đã sửa: string -> TEXT
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now() -- Đã sửa: upadte_at -> update_at
);
CREATE TABLE "nckh_bai_bao" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "du_an_id" BIGINT REFERENCES "nckh_du_an" ("id"),
    "chu_de_id" BIGINT REFERENCES "nckh_chu_de" ("id"),
    "linh_vuc_id" BIGINT REFERENCES "nckh_linh_vuc" ("id"),
    "tieu_de" TEXT,
    "tom_tat" TEXT,
    "ten_tap_chi" TEXT,
    "so_phat_hanh" VARCHAR(255),
    "ngay_xuat_ban" TIMESTAMP,
    "so_trang" BIGINT,
    "ma_doi" VARCHAR(255),
    "url" VARCHAR(255),
    "loai" INT,
    "ten_hoi_thao" TEXT,
    -- Đã sửa: string -> TEXT
    "dia_diem_hoi_thao" TEXT,
    -- Đã sửa: điaiem_hoithao -> dia_diem_hoi_thao, string -> TEXT
    "ngay_hoi_thao" DATE,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now(),
    -- Đã sửa: upadte_at -> update_at
    "status" INT -- Đã sửa: satatus -> status
);
CREATE TABLE "nckh_baibao_thanhvien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bai_bao_id" BIGINT REFERENCES "nckh_bai_bao" ("id"),
    "user_name" BIGINT,
    -- Đã sửa: uesr_name -> user_name
    "role_thanh_vien" TEXT,
    -- Đã sửa: string -> TEXT
    "vai_tro" INT,
    "ngay_tham_gia" TIMESTAMP,
    "ngay_roi_di" TIMESTAMP
);
CREATE TABLE "nckh_du_an_thanh_vien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "du_an_id" BIGINT REFERENCES "nckh_du_an" ("id"),
    "id_thanh_vien" BIGINT,
    "role_thanh_vien" TEXT,
    -- Đã sửa: string -> TEXT
    "vai_tro" INT,
    "ngay_tham_gia" TIMESTAMP,
    "ngay_roi_di" TIMESTAMP
);
CREATE TABLE "nckh_hoi_dong_danh_gia" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ma" TEXT,
    -- Đã sửa: string -> TEXT
    "ten_hoi_dong" TEXT,
    "loai_hoi_dong" TEXT,
    -- Đã sửa: string -> TEXT
    "url_quyet_dinh" TEXT,
    -- Đã sửa: string -> TEXT
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now(),
    -- Đã sửa: upadte_at -> update_at
    "deleted_at" TIMESTAMP
);
CREATE TABLE "nckh_hoi_dong_thanh_vien" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nhakhoahoc_id" BIGINT REFERENCES "nckh_nha_khoa_hoc" ("id"),
    "hoi_dong_id" BIGINT REFERENCES "nckh_hoi_dong_danh_gia" ("id"),
    "vai_tro" VARCHAR(255),
    "danh_gia" TEXT,
    "diem" INT,
    "ghi_chu" TEXT,
    "url_bien_ban" TEXT,
    "creat_at" TIMESTAMP DEFAULT now(),
    "update_at" TIMESTAMP DEFAULT now() -- Đã sửa: upadte_at -> update_at
);
CREATE TABLE "nckh_duan_file" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Sửa PK cho nhất quán
    "du_an_id" BIGINT REFERENCES "nckh_du_an" ("id"),
    "user_name_nguoi_tao" TEXT,
    -- Đã sửa: string -> TEXT
    "url" TEXT
);
CREATE TABLE "nckh_hoidong_duan" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Sửa PK cho nhất quán
    "hoidong_id" BIGINT REFERENCES "nckh_hoi_dong_danh_gia" ("id"),
    "duan_id" BIGINT REFERENCES "nckh_du_an" ("id")
);
CREATE TABLE "nckh_thongbao_file" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Sửa PK cho nhất quán
    "thongbao_id" BIGINT REFERENCES "nckh_thongbao_dexuat" ("id"),
    "ten" TEXT,
    -- Đã sửa: string -> TEXT
    "duong_dang" TEXT -- Đã sửa: string -> TEXT
);
-- Loại bỏ các ALTER TABLE vì các REFERENCES đã được thêm vào lúc tạo bảng
-- và lỗi logic FK đã được sửa.